### ISSUE TITLE
Develop integration for NP 2.0 headstage

### ISSUE THREAD

**Issue by glopesdev** [neurogears/onix-refactor#14]
- [x] #36
- [x] #37
- [x] #38
- [x] #86
- [x] #87

**Comment by jonnew** [comment]
Re opening so that the commits to issue-14 make more sense

**Comment by jonnew** [comment]
There is a lot of common code between Beta and public variants of the headstage. Specifically most, if not all, of the configuration is the same (shift register, register addresses, gain correction file contents and application, etc). What should we do about this? I feel like `static class NeuropixelsV2eBeta` should only hold things that are different from the public version (e.g. the GPIOConfig defaults) and everything else should go in `static class NeuropixelsV2e`. What do we think about that?
