### ISSUE TITLE
ConfigureTest0.Message not used

### ISSUE THREAD

**Issue by jonnew** [neurogears/onix-refactor#143]
https://github.com/neurogears/onix-refactor/blob/260149bdfb441c8d49a606bbfd303728cbc42bd0/OpenEphys.Onix/OpenEphys.Onix/ConfigureTest0.cs#L23

1. Should be tied to Message register via a subscription. 
2. Larger issue: should this device be removed from this package since we are not saying this package targets the FMC based system and this is a generic test device that is not actually included in this hardware?

**Comment by glopesdev** [comment]
@jonnew I wasn't aware this wasn't actually a device that was part of this hardware. In that case I agree it should definitely be removed as it will only cause confusion.
