### ISSUE TITLE
Run performance benchmarks for documentation

### ISSUE THREAD

**Issue by glopesdev** [neurogears/onix-refactor#16]
- [x] Run latency test and pinpoint bottleneck
- [x] Bandwidth test with load tester (test increasing both frame size and rate in fps independently):
  - 500 MB / s (maximum, may need to tweak block size up to 8k but can try up to 32k)
  - 300 MB / s
  - 100 MB / s (minimum)
  - Check buffer size

**Comment by jonnew** [comment]
The initial problem that spurred this issue was that the block read size was not being set correctly. This has been resolved. However, general performance benchmarks for both latency and bandwidth are valuable information and should be included in the documentation.

**Comment by glopesdev** [comment]
Closed via #73
