### ISSUE TITLE
io_reg declared outside of correct scope

### ISSUE THREAD

**Issue by jonnew** [neurogears/onix-refactor#49]
Is there a reason that `io_reg` is decarded outside of the function body of `SetIO`, which appears to be its full scope here:

https://github.com/neurogears/onix-refactor/blob/71557a06ca4b0e3820c6aa265ebd442d304c058e/OpenEphys.Onix/OpenEphys.Onix/ConfigureAnalogIO.cs#L198-L203

I'm creating a similar class to configure the electrical stimulator on Headstage64 and I want to make sure I'm understanding this.

**Comment by glopesdev** [comment]
@jonnew reading the code it seems to me that the `io_reg` variable is actually shared across all scopes of calls to the `SetIO` function, which is called for every channel. Basically it's saving the current global state of all bits, of which each channel sets only its own individual bits. Does the behavior of the device with that logic work as expected?

If it weren't for that shared behavior, I agree there would be no reason to have it sit outside the scope.
