### ISSUE TITLE
Add NameConverter functionality for headstages

### ISSUE THREAD

**Issue by bparks13** [neurogears/onix-refactor#81]
This issue is prompted by issue #26, and is currently being developed in PR #78 . 

We are beginning to abstract some of these Bonsai nodes so they are no longer straight reflections of hardware; that is, when the user is interacting with the `Rhs2116StimulusTrigger` node and updating stimulus sequence values, the node should be writing to the `Rhs2116` chips present in the `HeadstageRhs2116`. This is because the `Rhs2116` device is where the stimulus sequence registers physically reside, but it made logical sense to move the stimulus parameters to the `Rhs2116StimulusTrigger` from a user perspective.

Originally, stimulus sequence values were being modified in the `ConfigureRhs2116` node, which contained within it the device address and name for the `Rhs2116` itself. Therefore, there were no issues with updating device registers because the address was internal (this representation is still shown in branch [issue-26](https://github.com/neurogears/onix-refactor/blob/issue-26/OpenEphys.Onix/OpenEphys.Onix/ConfigureRhs2116.cs#L88)).

Now, since we are abstracting these nodes, we are attempting to modify `Rhs2116` devices from the `Rhs2116StimulusTrigger` device, which does not inherently know the addresses of the `Rhs2116` devices. Initially I assumed that we could define the address of the two `Rhs2116` chips as [relative addresses](https://github.com/bparks13/onix-refactor/blob/issue-26/OpenEphys.Onix/OpenEphys.Onix/Rhs2116StimulusTrigger.cs#L41C23-L42C99) from the `Rhs2116StimulusTrigger` device (i.e., the Rhs chips are -2 and -1 relative to the trigger); however, it would be best to link the attributes in some way so that we don't have this hard-coded assumption.

Now that we are trying to grab device addresses outside of the configure node, as well as from a completely different device, the question becomes: what is the best framework to use for setting and reading device names and/or addresses? 

1. Add two additional device names for the `Rhs2116A` and `Rhs2116B` in the `Rhs2116StimulusTrigger`, which would be public parameters, and require the user to select the correct devices from a drop-down menu. This would be the same process as normal, using the `Rhs2116.NameConverter` to link the device name across nodes. However, this could cause issues if the user inverts the A/B selection, or if there are two headstages connected a user could select a trigger from one headstage and an Rhs2116 from the other.
2. Hard-code the assumption that the headstage is in charge of addresses, and we can know the relative address of the `Rhs2116A/B` chips since we know the relationship between them. Already discussed above, this is not ideal.
3. Similar to (2), we hard-code the device names by assuming that the hub name is the same for all devices, so all we need to do is remove the `StimulusTrigger` from the string and replace it with `Rhs2116A` or `Rhs2116B` as needed. Similar concerns here as for (2), this is not ideal.
4. Add an abstracted layer in between the headstage and the individual devices that contains the three devices we care about here, which would have some `NameConverter` associated with it. The headstage would still be in charge of instantiating the devices, but it would also create and name this abstracted layer so that the `Rhs2116StimulusTrigger` can link to a single name/object. From this object, we would have access to the device names and addresses as they are created by the headstage, so we no longer have hard-coded assumptions and we don't rely on the user to correctly link multiple devices.
5. Similar to (4), we add a `NameConverter` for the headstage itself, so that we can access the headstage and the underlying devices. Again, this gives us access to the actual names and addresses without needing any assumptions.

Of these proposed solutions, (4) and (5) seem to make the most sense. I am not sure if one is more feasible than the other, or if there is another option out there that would make more sense to implement.

**Comment by glopesdev** [comment]
We ended up solving this by relying on meta-information about how device addresses are organized in the headstage, which were converted into static helper functions and constants which avoided the need to share state between the configure and streaming nodes. See #78 for details.
